import { ThemeProvider } from "@/context/themeContext";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "SYED BILAL",
  description: "Generated by create next app",
  icon: "./favicon.ico",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/" type="image/png" sizes="32x32" />

      </head>
      <ThemeProvider>
        <body suppressHydrationWarning={true}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
